# Generated by Django 4.2.7 on 2023-12-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cid',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
